### ISSUE TITLE
(Bug) Illegal characters in package.json for yarn

### ISSUE THREAD

**Issue by nathanielgreen** [JackOddy/React-Native-Skeleton#1]
Error running yarn start:

```
yarn run v1.1.0
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Proposed fix in `package.json`:

```
   2   "name": "counter-skeleton",
```

**Comment by JackOddy** [comment]
Hi nathanialgreen, 

Thanks for your issue! We're taken a look at the problem and we have agreed your proposed fix is the best solution at this time. Thank you for your help!

Kind regards

**Comment by nathanielgreen** [comment]
Jack,

Thanks Jack. Also it's nathani**e**lgreen.

Best Wishes for the Christmas Season,
Nathaniel Green
